### ISSUE TITLE
Needed: Export/import of entity definitions only

### ISSUE THREAD

**Issue by murugappanrm** [espocrm/ext-export-import#1]
Hi,

I do not know where to post. So i decided to post it here as this may get focused attention. Please allow me to provide the details:

Need for additional features. Please allow me to provide the details:

**(1) Problem Statement**

The existing version either exports an entity with all its data or exports all the customization done to an instance. We (in the ASEAN Group) feel that exporting all the customization may be a moot feature as we could already do this just by copying the custom->espo folder to the new instance. Exporting the entity with all its data may be one option for others but does not help people who want to re-engineer their systems.

**(2) Feature request:**

Provide additional parameter (--structure-only) where the extension can export only the customization related to the selected entity.

**(3) Use Case**

This feature is highly useful for people who want to re-engineer their CRM or who want extract and use only certain entities to an totally new instance serving another purpose.

There are many of us seeking this. Appreciate consideration and early enhancement to this extension.

**Comment by tmachyshyn** [comment]
@murugappanrm thanks for your request.

The described features were already in our to-do list. I am happy to inform that a new version 2.0.0 has been released with implementation of these and other features.

Please note the options are slightly different then in the v1, https://docs.espocrm.com/extensions/export-import/export-import-usage/#usage.

1. Added the ability to export / import without any data:

Export:

```
bin/command export-import export --format=json --path="./data/export-import" --skip-data --skip-config
```

Import:

```
bin/command export-import import --format=json --path="./data/export-import" --skip-data --skip-config
```

2. Added the ability to export / import customization for defined entities only:

Along with entity relationships:

```
bin/command export-import export --format=json --path="./data/export-import" --skip-data --skip-config --entity-list="Account"
```

without relationships:

```
bin/command export-import export --format=json --path="./data/export-import" --skip-data --skip-config --entity-list="Account" --skip-related-entities
```

3. Added, https://docs.espocrm.com/extensions/export-import/export-import-usage/#more-usage. Feel free to contribute more use cases.

**Comment by murugappanrm** [comment]
Hi @tmachyshyn 

Wow, that was quick and in time for my use. Great Job. One question, I am trying to export from V 7.2 to V8.1 would that work?

Please advise. Thank you

**Comment by tmachyshyn** [comment]
The minimum version of EspoCRM is v7.3.0.
You can upgrade your EspoCRM instance and then install the Export Import extension.

**Comment by murugappanrm** [comment]
Hi @tmachyshyn ,

To export from version < 7.3. As all i wanted was to export and import the customization only to another instance for re-engineering. This is what i did:


1. Create a 8.1.4 instance and copied the custom->espo folder to the new instance
2. Did a hard rebuild on the new instance
3. Used the export-import and exported the customization without the relationships.
4. Copied the exported folders to the instance which i was re-engineering
5. Perform the import.

Everything worked super well.  I greatly appreciate how much effort you have saved me. This cut down my re-engineering time by 45%. Thank you @tmachyshyn .
