### ISSUE TITLE
Export Import of Cases does not import layouts

### ISSUE THREAD

**Issue by murugappanrm** [espocrm/ext-export-import#2]
Hi @tmachyshyn ,

I exported the "Case" entity from one working instance and imported it into a new crm instance. I see that it imported all the links and field but did not import the layouts. 

This is the export command:

`php bin/command export-import export --format=json --path="./data/export-import" --skip-data --skip-config --entity-list="Case"`

This is the import command:

`php bin/command export-import import --format=json --path="./data/export-import" --import-type=createAndUpdate --skip-data --skip-config --entity-list="Case"`

I am not sure why? Please advise.

**Comment by tmachyshyn** [comment]
Fixed in v2.4.0.
Thanks
