### ISSUE TITLE
Export of Entities to another instance generates a warning

### ISSUE THREAD

**Issue by murugappanrm** [espocrm/ext-export-import#4]
Hi 

I test this extension many times it always generated the following warnings:

**[2024-05-08 06:03:08] WARNING: Link BpmnSignalListener.flowNode has no type.  
[2024-05-08 06:03:08] WARNING: Link GoogleCalendarRecurrentEvent.googleCalendarUser has no type.**  

And if i ignore and use the instance, i find that it all messed up an result in database integrity errors.

These are the CLI commands used:

```
php bin/command export-import export --format=json --path="./data/export-import" --skip-data --skip-config --entity-list="Appuser"

php bin/command export-import import --format=json --path="./data/export-import" --skip-data --skip-config --entity-list="Appuser"
```

**Comment by tmachyshyn** [comment]
Fixed in v2.3.1
